### PR TITLE
use % formatter in string format

### PR DESCRIPTION
**Pull request by EdwardBetts**
I just discovered the % formatter, it will multiple an input by 100, then add a % to the output.

### CODE REVIEW

**Comment by aerler** [comment]
Are you developing a GitHub crawler or how come you are forking my project? You don't seem to be a scientist... I'm just honestly curious.

**Comment by EdwardBetts** [comment]
No crawler, I used github code search to look for Python projects containing '0f}%".format(100'.

**Comment by aerler** [comment]
I see. Why the effort then? I appreciate the tip; I didn't know about this, but what's in it for you?

**Comment by EdwardBetts** [comment]
Like all open source, to make the world a better place. I wish somebody had told me about this feature five years ago.

**Comment by aerler** [comment]
Hm... maybe it's a sign of social decay that I immediately suspect a selfish motive when someone is trying to be helpful.
There are a lot of things I wish someone had told me 5 years ago! ;-)
Thanks anyway!

**Pull request merged**
