### PR TITLE
further modified GHCN.py

### PR DESCRIPTION
**Pull request by huoyiling**
add select function and changed station name read method

### CODE REVIEW

**Comment by aerler** [comment]
Why did you close this? Well... you Tibet box should not be hard-coded into this, so I guess you are fixing that?

**Comment by huoyiling** [comment]
I pushed my change twice so I closed the latter one. Can you see my first push which added select function and changed station name read method? If no, I will push that again.

**Comment by aerler** [comment]
This is currently the only open pull request. I can see your changes, but I don't want your Tibet box to be hard-coded. Please use the 'constraints' dictionary for this purpose. We should also use introduce something in the filename that distinguishes different sets of stations. We might want to use this dataset for different regions.

**Comment by aerler** [comment]
I'm going to merge this, but I want the latitude limits to be variable. I would like to try this dataset for North America. We probably have to add a few more selection tests to select for data availability (i.e. select a station that has data for a certain variable for a certain time period).

**Pull request merged**
